openapi: 3.0.3
info:
  title: API文档
  version: 1.0.0
externalDocs:
  description: 参考配置
  url: https://editor.swagger.io/
tags:
  - name: home
    description: 首页 - 相关接口
  - name: goods-list
    description: 商品列表 - 相关接口
  - name: goods-detail
    description: 商品详情 - 相关接口
  - name: message-board
    description: 留言 - 相关接口
  - name: user
    description: 用户 - 相关接口
  - name: shopping-cart
    description: 购物车 - 相关接口
  - name: goods-evaluate
    description: 商品评价 - 相关接口
  - name: order
    description: 订单 - 相关接口
  - name: goods-collection
    description: 商品收藏 - 相关接口
  - name: address
    description: 地址 - 相关接口
  - name: admin/brands
    description: 品牌 - 管理后台相关接口
  - name: admin/order
    description: 订单 - 管理后台相关接口
  - name: admin/goods-evaluate
    description: 商品评价 - 管理后台相关接口
  - name: admin/goods
    description: 商品 - 管理后台相关接口
  - name: admin/user
    description: 用户 - 管理后台相关接口
  - name: admin/permission
    description: 权限 - 管理后台相关接口
paths:
  /public/hot-recommendations:
    get:
      tags:
        - user
      summary: 查询 - 热门推荐商品
      description: ''
      operationId: hotRecommendations
      parameters:
      responses:
        '200':
          description: 成功返回数据
        '500':
          description: 操作失败
